version: '3.3'

services:
  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: veiculos
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: 
      context: .
      dockerfile: src/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
    - keycloak

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
