version: '3.3'

services:
  backend:
    build: 
      context: .
      dockerfile: src/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network2
    env_file:
      - .env

networks:
  app-network2:
    external: true