version: '3.3'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network2

networks:
  app-network2:
    external: true