version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: veiculos
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network2
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network2:
    external: true

volumes:
  mysql-data: