version: '3.3'

services:
  runner:
    image: ubuntu:20.04
    container_name: runner
    stdin_open: true
    tty: true
    networks:
      - app-network2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Monta o socket Docker do host no container
      - .:/workspace # Monta o diretório do projeto no container
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Configura o Docker para usar o socket do host
    command: >
      bash -c "
      apt update && apt install -y curl vim perl docker-compose &&
      cd /workspace &&
      docker-compose -f docker-compose.mysql.yml up -d &&
      docker-compose -f docker-compose.keycloak.yml up -d &&
      docker-compose -f docker-compose.backend.yml up -d &&
      tail -f /dev/null
      "
networks:
  app-network2:
    external: true