version: '3.3'

services:
  runner:
    image: ubuntu:20.04
    container_name: runner
    stdin_open: true
    tty: true
    networks:
      - runner-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Monta o socket Docker do host no container
      - .:/workspace # Monta o diretório do projeto no container
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Configura o Docker para usar o socket do host

networks:
  runner-network:
    driver: bridge