version: '3.3'

services:
  keycloak:
    container_name: keycloak
    build:
      context: ./docker/keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - app-network2

networks:
  app-network2:
    external: true