name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install

      # - name: Run Tests
      #   run: npm test

      # - name: Run Tests
      #   run: npm test -- --coverage

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fix Docker Permissions
        run: |
          sudo chmod 666 /var/run/docker.sock || true
          sudo usermod -aG docker $(whoami) || true
      - name: Fix Docker Permissions
        run: |
          docker-compose -f /workspace/docker-compose.backend.yml down
          docker rmi workspace_backend
          docker-compose -f docker-compose.backend.yml build --no-cache

      - name: Deploy Application
        run: |
          docker-compose -f /workspace/docker-compose.backend.yml up -d