name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Services
        run: docker-compose up -d

      - name: Wait for Services
        run: |
          until nc -z localhost 3306; do
            echo "Waiting for database...";
            sleep 5;
          done
          until nc -z localhost 8080; do
            echo "Waiting for Keycloak...";
            sleep 5;
          done

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

      # - name: Run Tests
      #   run: npm test -- --coverage

      - name: Build Project
        run: npm run build

      - name: Stop Services
        run: docker-compose down

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          docker-compose -f /workspace/docker-compose.yml up -d --build backend
          docker-compose logs -f backend
